moving old files to old_scripts --> causing an issue AttributeError: module 'numpy' has no attribute 'dtype'
- issue says that it's because of a bad install of numpy? unsure why this is happening, looking into it further (https://stackoverflow.com/questions/55108902/module-numpy-has-no-attribute-dtype) solution on stackoverflow doesn't work